title:  XuMengTing's Web
tagline:  宁静致远

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: '笔记', path: 'menu', url: 'writing.html'}
- {name: '项目', path: 'menu', url: 'project.html'}
- {name: '关于', path: 'menu', url: 'about.html'}
- {name: '方式', path: 'menu', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/xmtgithub123'}
- {icon: 'wechat', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
